openapi: '3.0.2'
info:
  title: Wallet By HEI API
  description: |
    This project consists of a Java API for managing accounts, transactions, and currencies for a financial management
    application. It uses Java for the backend, a PostgreSQL database to store the data, and exposes endpoints to interact
    with this data
  version: '1.0'
servers:
  - url: https://wallet-by-HEI/v1
paths:
  /currencies:
    get:
      summary: Retrieve all currencies
      description: Retrieve a list of available currencies
      operationId: getAllCurrencies
      responses:
        '200':
          description: A list of currencies
          content:
            application.json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '400':
          description: Currencies not found
          content:
            application.json:
              example:
                message: 'No currencies found in the System'
components:
  schemas:
    Currency:
      type: object
      properties:
        currency_id:
          type: integer
          format: int64
          description: The unique identifier for the currency
        currency_name:
          type: string
          description: The name of the currency
