openapi: 3.0.3
info:
  title: Wallet By HEI API
  description: |
    This project consists of a Java API for managing accounts, transactions, and currencies for a financial management
    application. It uses Java for the backend, a PostgreSQL database to store the data, and exposes endpoints to interact
    with this data
  version: 'latest'
servers:
  - url: https://wallet-by-HEI/v1
tags:
  - name: Currencies
    description: Endpoints related to currencies
  - name: Accounts
    description: Endpoints related to user accounts
  - name: Transactions
    description: Endpoints related to transactions
paths:
  /currencies:
    get:
      tags:
        - Currencies
      summary: Retrieve all currencies
      description: Retrieve a list of available currencies
      parameters:
        - name: page
          in: query
          schema:
            $ref: '#/components/schemas/Page'
        - name: page_size
          in: query
          schema:
            $ref: '#/components/schemas/PageSize'
        - name: currency_name
          in: query
          description: 'Filter currencies by name, case is ignored'
          schema:
            type: string
      operationId: getAllCurrencies
      responses:
        '200':
          description: A list of currencies
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Currency'
    post:
      tags:
        - Currencies
      summary: Add a new currency
      description: Add a new currency to the System
      operationId: addCurrency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCurrency'
      responses:
        '200':
          description: Currency added successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
    put:
      tags:
        - Currencies
      summary: Update an existing currency
      description: Update a existing currency in a the system
      operationId: updateCurrency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCurrency'
      responses:
        '200':
          description: Currency updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Currency'
  /accounts:
    get:
      tags:
        - Accounts
      summary: Retrieve all accounts
      description: Retrieve a list of all user accounts
      parameters:
        - name: page
          in: query
          schema:
            $ref: '#/components/schemas/Page'
        - name: page_size
          in: query
          schema:
            $ref: '#/components/schemas/PageSize'
        - name: first_name
          in: query
          description: 'Filter account by first_name, case is ignored'
          schema:
            type: string
        - name: last_name
          in: query
          description: 'Filter account by last_name, case is ignored'
          schema:
            type: string
      operationId: getAllAccount
      responses:
        '200':
          description: A list of account
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    post:
      tags:
        - Accounts
      summary: Create a new account
      description: Create a new user account
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAccount'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
    put:
      tags:
        - Accounts
      summary: Update an existing account
      description: Update an existing user account
      operationId: updateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccount'
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
  /transactions:
    get:
      tags:
        - Transactions
      summary: Retrieve all transactions
      description: Retrieve a list of all transactions
      parameters:
        - name: page
          in: query
          schema:
            $ref: '#/components/schemas/Page'
        - name: page_size
          in: query
          schema: 
            $ref: '#/components/schemas/PageSize'
      operationId: getAllTransactions
      responses:
        '200':
          description: A list of transaction
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
    post:
      tags:
        - Transactions
      summary: Create a new transaction
      description: Create a new transaction entry
      operationId: createTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTransaction'
      responses:
        '200':
          description: Transation created successfully
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/Currency'
components:
  schemas:
    Currency:
      type: object
      properties:
        currency_id:
          type: integer
          description: The unique identifier for the currency
        currency_name:
          type: string
          description: The name of the currency
    NewCurrency:
      type: object
      properties:
        currency_name:
          type: string
          description: The name of the new currency
    UpdateCurrency:
      type: object
      properties:
        currency_id:
          type: integer
          description: The ID of the currency to be updated.
        currency_name:
          type: string
          description: The updated name of the currency.
      required:
        - currency_id
    Account:
      type: object
      properties:
        account_id:
          type: integer
          description: The unique identifier for the account
        first_name:
          type: string
          description: The first name of the account holder
        last_name:
          type: string
          description: The last name of the account holder
        password:
          type: string
          description: The password for the account
        balance:
          type: number
          description: The current balance in the account
        currency_id:
          type: integer
          description: The ID of the currency associated with the account
    NewAccount:
      type: object
      properties:
        first_name:
          type: string
          description: The first name of the new account holder.
        last_name:
          type: string
          description: The last name of the new account holder.
        password:
          type: string
          description: The password for the new account.
        balance:
          type: number
          description: The initial balance for the new account.
        currency_id:
          type: integer
          description: The ID of the currency associated with the new account.
    UpdateAccount:
      type: object
      properties:
        account_id:
          type: integer
          description: The ID of the account to be updated.
        first_name:
          type: string
          description: The updated first name of the account holder.
        last_name:
          type: string
          description: The updated last name of the account holder.
        password:
          type: string
          description: The updated password for the account.
        balance:
          type: number
          format: float
          description: The updated balance in the account.
        currency_id:
          type: integer
          description: The updated ID of the currency associated with the account.
      required:
        - account_id
    Transaction:
      type: object
      properties:
        transaction_id:
          type: integer
          description: The unique identifier for the transaction
        transaction_date:
          type: string
          format: date
          description: The date of the transaction
        amount:
          type: number
          format: float
          description: The transaction amount
        description:
          type: string
          description: The description of the transaction
        account_id:
          type: integer
          description: The ID of the account associated with the transaction
    NewTransaction:
      type: object
      properties:
        transaction_date:
          type: string
          format: date
          description: The date of the new transaction.
        amount:
          type: number
          format: float
          description: The amount for the new transaction.
        description:
          type: string
          description: The description for the new transaction.
        account_id:
          type: integer
          description: The ID of the account associated with the new transaction.
    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type: 
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        type: BadRequestException
        message: Bad request
  responses:
    '400': 
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestException'