openapi: '3.0.2'
info:
  title: Wallet By HEI API
  description: This project consists of a Java API for managing accounts, transactions, and currencies for a financial management application. It uses Java for the backend, a PostgreSQL database to store the data, and exposes endpoints to interact with this data
  version: '1.0'
servers:
  - url: https://wallet-by-HEI/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
