openapi: '3.0.2'
info:
  title: Wallet By HEI API
  description: |
    This project consists of a Java API for managing accounts, transactions, and currencies for a financial management
    application. It uses Java for the backend, a PostgreSQL database to store the data, and exposes endpoints to interact
    with this data
  version: '1.2'
servers:
  - url: https://wallet-by-HEI/v1
paths:
  /currencies:
    get:
      summary: Retrieve all currencies
      description: Retrieve a list of available currencies
      operationId: getAllCurrencies
      responses:
        '200':
          description: A list of currencies
          content:
            application.json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Currency'
        '404':
          description: Currencies not found
          content:
            application.json:
              example:
                message: 'No currencies found in the System'
    post:
      summary: Add a new currency
      description: Add a new currency to the System
      operationId: addCurrency
      requestBody:
        required: true
        content:
          application.json:
            schema:
              $ref: '#/components/schemas/NewCurrency'
      responses:
        '201':
          description: Currency added successfully
        '400':
          description: Invalid input
          content:
            application/json:
              example:
                message: 'Invalid currency data provided'
        '409':
          description: Currency already exists
          content:
            application/json:
              example:
                message: 'Currency with the provided name already exists'
  /account:
    get:
      summary: Retrieve all accounts
      description: Retrieve a list of all user accounts
      operationId: getAllAccount
      responses:
        '200':
          description: A list of account
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '404':
          description: No accounts found
          content:
            application/json:
              example:
                message: 'No accounts found in the system'
components:
  schemas:
    Currency:
      type: object
      properties:
        currency_id:
          type: integer
          format: int64
          description: The unique identifier for the currency
        currency_name:
          type: string
          description: The name of the currency
    NewCurrency:
      type: object
      properties:
        currency_name:
          type: string
          description: The name of the new currency
    Account:
      type: object
      properties:
        account_id:
          type: integer
          description: The unique identifier for the account.
        first_name:
          type: string
          description: The first name of the account holder.
        last_name:
          type: string
          description: The last name of the account holder.
        password:
          type: string
          description: The password for the account.
        balance:
          type: number
          description: The current balance in the account.
        currency_id:
          type: integer
          description: The ID of the currency associated with the account.
